// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf73dIIMnOowIc4-Ni4X59DypFsXFbqKQ',
    appId: '1:8592950519:web:2b1b642a42a714917efff2',
    messagingSenderId: '8592950519',
    projectId: 'food-app-e304c',
    authDomain: 'food-app-e304c.firebaseapp.com',
    storageBucket: 'food-app-e304c.appspot.com',
    measurementId: 'G-2MXN5MW9C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoT1Hvox06Rou-YBs-LzHKDz64UCsUJtw',
    appId: '1:8592950519:android:851cd56f4486a5497efff2',
    messagingSenderId: '8592950519',
    projectId: 'food-app-e304c',
    storageBucket: 'food-app-e304c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9IeQpWV0bn8snGugZgC2y4_FxmlBvofg',
    appId: '1:8592950519:ios:cc013c40f94723567efff2',
    messagingSenderId: '8592950519',
    projectId: 'food-app-e304c',
    storageBucket: 'food-app-e304c.appspot.com',
    iosBundleId: 'com.example.flutterFoodApp',
  );
}
